### ISSUE TITLE
Path issue with conda install

### ISSUE THREAD

**Issue by jdmanthey** [cguyomar/MinYS#1]
Just wanted to let you know that with the conda install, the path to graph_simplification.py in the MinYS.py script didn't work. I changed "graph_simplification/graph_simplification.py" on line 360 of MinYS.py to "graph_simplification.py" and the entire pipeline worked. 

The tool seems to work nicely. Thanks!

**Comment by cguyomar** [comment]
Hi Joe,

Thanks for noticing, it should be fixed in the latest Bioconda build.
