### ISSUE TITLE
 No module named 'genome_graph'

### ISSUE THREAD

**Issue by karinedurand** [cguyomar/MinYS#3]
Hi,
I try to use script gfa2fasta.py, but i can't find module genome_graph.
How install it? I try pip install but can't find this module.
Best
Karine

**Comment by cguyomar** [comment]
Hi Karine,

This module is packaged with MinYS.
The easiest way to use it may be to install MinYS with Conda, and then you'll be able to use that script.

Best,
Cervin

**Comment by clemaitre** [comment]
Hi Karine,

it should also work if the `genome_graph/` directory from this repository is located in the same directory as the `gfa2fasta.py` file (as it is organized in this repository, if you cloned it).

Best,
Claire
